GRANT ALTER ANY INDEX TO STORE_DEV;
GRANT CREATE ANY INDEX TO STORE_DEV;
GRANT DROP ANY INDEX TO STORE_DEV;

GRANT ALTER ANY SEQUENCE TO STORE_DEV;
GRANT CREATE ANY SEQUENCE TO STORE_DEV;
GRANT DROP ANY SEQUENCE TO STORE_DEV;

GRANT CREATE ANY TABLE TO STORE_DEV;
GRANT ALTER ANY TABLE TO STORE_DEV;
GRANT DROP ANY TABLE TO STORE_DEV;
GRANT SELECT ANY TABLE TO STORE_DEV;
GRANT DELETE ANY TABLE TO STORE_DEV;
GRANT INSERT ANY TABLE TO STORE_DEV;
GRANT UPDATE ANY TABLE TO STORE_DEV;

GRANT ALTER ANY TRIGGER TO STORE_DEV;
GRANT CREATE ANY TRIGGER TO STORE_DEV;
GRANT DROP ANY TRIGGER TO STORE_DEV;

GRANT CREATE ANY SYNONYM TO STORE_DEV;
GRANT CREATE PUBLIC SYNONYM TO STORE_DEV;

GRANT CREATE ANY VIEW TO STORE_DEV;
GRANT DROP ANY VIEW TO STORE_DEV;

GRANT CREATE PROCEDURE TO STORE_DEV;
GRANT ALTER ANY PROCEDURE TO STORE_DEV;

GRANT QUERY REWRITE TO STORE_DEV;
